name: Compile Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Configuring git environment.
         run: |
            git config --global user.name pachof
            git config --global user.email pachomasto2009@gmail.com

       - name: Building Kernel.
         run: |
             git clone --depth 1 https://github.com/pachof/kernel_xiaomi_ginkgo_neutrino_modernium.git -b Android11 kernel
             cd kernel
             chmod 777 Build-A11.sh
             ./Build-A11.sh

       - name: Uploading ZIP.
         run: |
             cd kernel
             curl -T *.zip https://pixeldrain.com/api/file/ && echo ""
       - name: Upload to Release
         uses: softprops/action-gh-release@v1
         with:
           files: |
             kernel/*.zip
           name: kernel-${{ github.run_id }}
           tag_name: ${{ github.run_id }}
           body: |
             Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
