name: Compile Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Configuring git environment.
         run: |
            git config --global user.name tejas101k
            git config --global user.email tejassingh649@rediffmail.com

       - name: Building Kernel.
         run: |
             git clone --depth 1 https://github.com/pachof/kernel_xiaomi_ginkgo_neutrino_modernium.git -b qpr2 kernel
             cd kernel
             chmod 777 build.sh
             ./build.sh

       - name: Uploading ZIP.
         run: |
             cd kernel
             curl -T RyzenKernel-AOSP-Ginkgo-*.zip https://pixeldrain.com/api/file/ && echo "
